import type { ShipmentForm } from "./types"

export const DRAFT_KEY = "federalogistic_shipment_draft"

export const statusOptions = ["Order Confirmed", "Package received by Federalogistic", "Out for Delivery", "Custom Hold", "Delivered"]
export const paymentOptions = ["paid", "unpaid", "pending"]

export const CURRENCIES: { code: string; name: string }[] = [
  { code: "USD", name: "US Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "British Pound" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "DKK", name: "Danish Krone" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "INR", name: "Indian Rupee" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "ZAR", name: "South African Rand" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "KRW", name: "South Korean Won" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "THB", name: "Thai Baht" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "VND", name: "Vietnamese Dong" },
  { code: "TWD", name: "Taiwan Dollar" },
  { code: "AED", name: "UAE Dirham" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "QAR", name: "Qatari Riyal" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "BHD", name: "Bahraini Dinar" },
  { code: "OMR", name: "Omani Rial" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "ILS", name: "Israeli New Shekel" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "MAD", name: "Moroccan Dirham" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "NGN", name: "Nigerian Naira" },
  { code: "GHS", name: "Ghanaian Cedi" },
  { code: "KES", name: "Kenyan Shilling" },
  { code: "TZS", name: "Tanzanian Shilling" },
  { code: "UGX", name: "Ugandan Shilling" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "XOF", name: "West African CFA Franc" },
  { code: "XAF", name: "Central African CFA Franc" },
  { code: "AOA", name: "Angolan Kwanza" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "MZN", name: "Mozambican Metical" },
  { code: "RWF", name: "Rwandan Franc" },
  { code: "SDG", name: "Sudanese Pound" },
  { code: "MUR", name: "Mauritian Rupee" },
  { code: "SCR", name: "Seychellois Rupee" },
  { code: "MGA", name: "Malagasy Ariary" },
  { code: "CVE", name: "Cape Verdean Escudo" },
  { code: "GMD", name: "Gambian Dalasi" },
  { code: "GNF", name: "Guinean Franc" },
  { code: "SLL", name: "Sierra Leonean Leone" },
  { code: "LRD", name: "Liberian Dollar" },
  { code: "CDF", name: "Congolese Franc" },
  { code: "BIF", name: "Burundian Franc" },
  { code: "DJF", name: "Djiboutian Franc" },
  { code: "SOS", name: "Somali Shilling" },
  { code: "COP", name: "Colombian Peso" },
  { code: "PEN", name: "Peruvian Sol" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "ARS", name: "Argentine Peso" },
  { code: "BOB", name: "Bolivian Boliviano" },
  { code: "PYG", name: "Paraguayan Guaraní" },
  { code: "UYU", name: "Uruguayan Peso" },
  { code: "GYD", name: "Guyanese Dollar" },
  { code: "SRD", name: "Surinamese Dollar" },
  { code: "TTD", name: "Trinidad & Tobago Dollar" },
  { code: "JMD", name: "Jamaican Dollar" },
  { code: "BBD", name: "Barbadian Dollar" },
  { code: "BSD", name: "Bahamian Dollar" },
  { code: "BZD", name: "Belize Dollar" },
  { code: "GTQ", name: "Guatemalan Quetzal" },
  { code: "HNL", name: "Honduran Lempira" },
  { code: "NIO", name: "Nicaraguan Córdoba" },
  { code: "CRC", name: "Costa Rican Colón" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "HTG", name: "Haitian Gourde" },
  { code: "CUP", name: "Cuban Peso" },
  { code: "XCD", name: "Eastern Caribbean Dollar" },
  { code: "AWG", name: "Aruban Florin" },
  { code: "KYD", name: "Cayman Islands Dollar" },
  { code: "PLN", name: "Polish Złoty" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "HUF", name: "Hungarian Forint" },
  { code: "RON", name: "Romanian Leu" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "HRK", name: "Croatian Kuna" },
  { code: "RSD", name: "Serbian Dinar" },
  { code: "BAM", name: "Bosnia-Herzegovina Mark" },
  { code: "MKD", name: "Macedonian Denar" },
  { code: "ALL", name: "Albanian Lek" },
  { code: "ISK", name: "Icelandic Króna" },
  { code: "UAH", name: "Ukrainian Hryvnia" },
  { code: "BYN", name: "Belarusian Ruble" },
  { code: "MDL", name: "Moldovan Leu" },
  { code: "GEL", name: "Georgian Lari" },
  { code: "AMD", name: "Armenian Dram" },
  { code: "AZN", name: "Azerbaijani Manat" },
  { code: "KZT", name: "Kazakhstani Tenge" },
  { code: "UZS", name: "Uzbekistani Som" },
  { code: "TMT", name: "Turkmenistani Manat" },
  { code: "KGS", name: "Kyrgyzstani Som" },
  { code: "TJS", name: "Tajikistani Somoni" },
  { code: "AFN", name: "Afghan Afghani" },
  { code: "PKR", name: "Pakistani Rupee" },
  { code: "BDT", name: "Bangladeshi Taka" },
  { code: "LKR", name: "Sri Lankan Rupee" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "MVR", name: "Maldivian Rufiyaa" },
  { code: "BTN", name: "Bhutanese Ngultrum" },
  { code: "MMK", name: "Myanmar Kyat" },
  { code: "KHR", name: "Cambodian Riel" },
  { code: "LAK", name: "Lao Kip" },
  { code: "MNT", name: "Mongolian Tögrög" },
  { code: "IQD", name: "Iraqi Dinar" },
  { code: "IRR", name: "Iranian Rial" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "YER", name: "Yemeni Rial" },
  { code: "LBP", name: "Lebanese Pound" },
  { code: "FJD", name: "Fijian Dollar" },
  { code: "PGK", name: "Papua New Guinean Kina" },
  { code: "SBD", name: "Solomon Islands Dollar" },
  { code: "VUV", name: "Vanuatuan Vatu" },
  { code: "WST", name: "Samoan Tālā" },
  { code: "TOP", name: "Tongan Paʻanga" },
  { code: "XPF", name: "CFP Franc" },
]

export const currencyOptions = CURRENCIES.map((c) => `${c.code} - ${c.name}`)

export const SHIPMENT_REQUIRED: (keyof ShipmentForm)[] = [
  "senderName", "senderEmail", "senderPhone", "senderAddress",
  "receiverName", "receiverEmail", "receiverPhone", "receiverAddress",
  "originLocation", "destinationLocation",
  "currentStatus", "packageType", "shipmentType", "weight", "itemDescription",
  "dateShipped", "pickupDate", "expectedDeliveryDate",
  "shippingCost", "clearanceCost", "totalCost",
  "paymentStatus", "deliveryMode", "comment",
]

export const emptyForm: ShipmentForm = {
  senderName: "",
  senderEmail: "",
  senderPhone: "",
  senderAddress: "",
  receiverName: "",
  receiverEmail: "",
  receiverPhone: "",
  receiverAddress: "",
  originLocation: "",
  originLat: "34.6937",
  originLng: "135.5023",
  currentLocation: "",
  currentLat: "",
  currentLng: "",
  destinationLocation: "",
  destinationLat: "-37.8136",
  destinationLng: "144.9631",
  currentStatus: "Order Confirmed",
  packageType: "",
  shipmentType: "Air Freight",
  weight: "",
  itemDescription: "",
  dateShipped: "",
  pickupDate: "",
  expectedDeliveryDate: "",
  shippingCost: "",
  clearanceCost: "",
  totalCost: "",
  currency: "USD - US Dollar",
  paymentStatus: "unpaid",
  deliveryMode: "Air Freight",
  comment: "",
  isOnHold: "false",
  addTransitMilestone: "false",
  addOnTheWayMilestone: "false",
  milestoneDate: "",
}
